# log frequency
val_check_interval: 1.0
progress_bar_refresh_rate: 5

wandb:
  project: wikineural
  entity: generationary
  log_model: True
  name: ${data.datamodule.source}-${data.datamodule.language}-${train.seed_idx}
  mode: 'online'

wandb_watch:
  log: 'all'
  log_freq: 100

lr_monitor:
  logging_interval: "step"
  log_momentum: False

monitor_padding: false
